
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rohithputha
 */

public class userstartpage extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    Userobjclass userobj;
    ButtonGroup g1=new ButtonGroup();
    Trie trieA;
    Trie trieB;
    ArrayList<String> arlist;
    ArrayList<String> arlist1;
    JTable jtableA;
    JTable jtableB;
    public userstartpage(Userobjclass user)
    {
        initComponents();
        userobj=user;
        g1.add(jRadioButton1);
        g1.add(jRadioButton2);
        trieA=new Trie();
        trieB=new Trie();
    }
    
    
    public userstartpage() {
        initComponents();
          g1.add(jRadioButton1);
        g1.add(jRadioButton2);
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jRadioButton1.setText("Name");

        jRadioButton2.setText("Author");

        jLabel1.setText("Search By");

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Log out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1)
                                .addGap(28, 28, 28)
                                .addComponent(jRadioButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel1))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Profile(userobj).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       new LoginPage1().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        if(jRadioButton1.isSelected())
       {
           String pretext=jTextField1.getText();
           trieB=new Trie();
           arlist=trieB.control(pretext);
           String[] list=(String[]) arlist.toArray(new String[arlist.size()]);
           String[][] data= new String[arlist.size()][3];
           String[] column={"Name","Author","Location"};
           for(int i=0;i<arlist.size();i++){
               data[i][0]=arlist.get(i);
               String ucode=userobj.dr.Ntou.get(arlist.get(i));
               data[i][1]=userobj.dr.utoA.get(ucode);
               data[i][2]=userobj.dr.utol.get(ucode);
               
           }
          
           
           jtableA=new JTable(data,column) {
           public boolean editCellAt(int row, int column, java.util.EventObject e) {
            return false;
            }
           };
    
           
           jPanel1.removeAll();
           jPanel1.setLayout(new FlowLayout());
           jPanel1.add(new JScrollPane(jtableA));
           add(jPanel1);
           revalidate();
           repaint();
           jPanel1.setVisible(true);
           setVisible(true);
           
            jtableA.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() == 2) {
            JTable target = (JTable)e.getSource();
            int row = target.getSelectedRow();
            new dialogbox(userobj.dr.Ntou.get(data[row][0]),userobj.returnidno(),userobj,1);
            }
           }
           });
  
           
       }
        
        else if(jRadioButton2.isSelected())
     {
         
         String pretext=jTextField1.getText();
         trieA=new Trie();
         arlist1=trieA.controlA(pretext);
         int sz=0;
         
         
         try{
         for(int i=0;i<arlist1.size();i++){
             ArrayList<String> ucodes=userobj.dr.Atou.get(arlist1.get(i));
             sz=sz+ucodes.size();
             }
         }
         catch(Exception e){System.out.println("error:1");}
         
         String[][] data=new String[sz][3];
         
         int l=0;
         try{
         for (int i=0;i<arlist1.size();i++){
             ArrayList<String> ucodes=userobj.dr.Atou.get(arlist1.get(i));
             for (int j=0;j<ucodes.size();j++){
                 String ucode=ucodes.get(j);
                 String name=userobj.dr.utoN.get(ucode);
                 String author=userobj.dr.utoA.get(ucode);
                 String location=userobj.dr.utol.get(ucode);
                 
                 if(!userobj.dr.utobn.get(ucode).equals("0")){
                 data[l][0]=name;
                 data[l][1]=author;
                 data[l][2]=location;
                 l++;
                 }
             }
         }
         }
         catch(Exception e){System.out.println("error:2");}
         String[] column={"Name","Author","location"};
         
         
         
         
         jtableA=new JTable(data,column){
           public boolean editCellAt(int row, int column, java.util.EventObject e) {
            return false;
            }
           };
      
        
         jPanel1.removeAll();
         jPanel1.setLayout(new FlowLayout());
         jPanel1.add(new JScrollPane(jtableA));
         add(jPanel1);
         revalidate();
         repaint();
         jPanel1.setVisible(true);
         setVisible(true);
         
          jtableA.addMouseListener(new MouseAdapter() {
       public void mouseClicked(MouseEvent e) {
       if (e.getClickCount() == 2) {
        JTable target = (JTable)e.getSource();
        int row = target.getSelectedRow();
        new dialogbox(userobj.dr.Ntou.get(data[row][0]),userobj.returnidno(),userobj,1);
        
        }
       }
      });
  
         
     }   
     
      
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
   
  
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userstartpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userstartpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userstartpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userstartpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userstartpage().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
